[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jun-hyeok/SUP5001-41_Deep-Neural-Networks_2022Spring/blob/main/DNN_HW4/pt_2.ipynb)

# DNN HW4 : Part 2

2022.03.16
박준혁

In [1]:
import numpy as np
import torch

from util import *

## Part 2: Exercise

##### 2-1. Use numpy to generate an array with values from 10 to 49
(ex. 10, 11, ... 49)

In [2]:
print("2-1", color=GRAY)

# numpy array with 10 to 49
a = np.arange(10, 50)
print(f"{a = }")

2-1
a = array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])


##### 2-2.  Use numpy to generate an array with values from 49 to 10 
(ex. 49, 48, ... 10)

In [3]:
print("2-2", color=GRAY)

# numpy array with 49 to 10
a = np.arange(49, 10, -1)
print(f"{a = }")

2-2
a = array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11])


##### 2-3 Find an array of indices with the same elements in a and b
(Hint: np.where)

In [4]:
print("2-3", color=GRAY)

# input
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
print(f"{a = }", color=GRAY, input=True)
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print(f"{b = }", color=GRAY, input=True)

# output: find an array of indices with the same elements in a and b.
print(f"{np.where(a == b)[0] = }")

2-3
>>>a = array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
>>>b = array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])
np.where(a == b)[0] = array([1, 3, 5, 7])


##### 2-4. Use broadcasting to find the result of adding 1 to a

In [5]:
print("2-4", color=GRAY)

# input
a = np.arange(9).reshape(3, 3)

# output: a + 1 using broadcasting
print(f"{a + 1 = }")

2-4
a + 1 = array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


##### 2-5. Change the first and second rows of a

In [6]:
print("2-5", color=GRAY)

# input
a = np.arange(9).reshape(3, 3)

# output: change the first and second rows of a
print(f"{a[[1, 0, *range(a.shape[0])[2:]], :] = }")

2-5
a[[1, 0, *range(a.shape[0])[2:]], :] = array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])


##### 2-6. Find a for the following output

In [7]:
print("2-6", color=GRAY)

# output
print("a.shape = (2, 3, 4)", color=GRAY)
print(f"a = {np.arange(24).reshape(2, 3, 4)}", color=GRAY)

# input
a = input("a = ")
print(f"{a = !s}", input=True)
a = eval(a)

print(f"{a.shape = }")
print(f"{a = }")

2-6
a.shape = (2, 3, 4)
a = [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
>>>a = np.arange(24).reshape(2, 3, 4)
a.shape = (2, 3, 4)
a = array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])


##### 2-7. Slice a for the following output

In [8]:
print("2-7", color=GRAY)

# output
print(f"{a[0, 1:, 2:]}", color=GRAY)

# input
idx = input("a[???] << ")
print(f"a[{idx}]", input=True)
print(eval(f"a[{idx}]"))

2-7
[[ 6  7]
 [10 11]]
>>>a[0, 1:, 2:]
[[ 6  7]
 [10 11]]


##### 2-8. Use torch.view to get the following output

In [9]:
print("2-8", color=GRAY)

import torch
import numpy as np

t = np.arange(24)
floatT = torch.FloatTensor(t)

# output
print(f"{t.shape = }", color=GRAY)
print(f"{floatT.view([-1, 6])[2:, (1, 4)]}", color=GRAY)

# input
arg = input("floatT.view([???])[] << ")
idx = input("floatT.view([])[???] << ")
print(f"floatT.view([{arg}])[{idx}]", input=True)
print(eval(f"floatT.view([{arg}])[{idx}]"))

2-8
t.shape = (24,)
tensor([[13., 16.],
        [19., 22.]])
>>>floatT.view([-1, 6])[2:, (1, 4)]
tensor([[13., 16.],
        [19., 22.]])
